const chooseSelect = require('./helpers/select.cjs');
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');

(async () => {
  const browser = await chromium.launch();
  try {
    fs.mkdirSync('tmp/pcd', { recursive: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const base = process.env.BASE_URL || 'http://127.0.0.1:4318';
    await page.emulateMedia({ reducedMotion: 'reduce' });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${base}/users/sign_in`);
    await page.locator('#user_email').fill('user_one@example.com');
    await page.locator('#user_password').fill('password');
    await page.locator('input[type="submit"]').click();
    await page.waitForURL(url => !url.pathname.includes('sign_in'));
    await page.goto(`${base}/escala-folgas?tab=coverage&date=2026-10-02`);
    await page.waitForURL(url => url.pathname === '/pcd');
    await page.locator('.pcd-route').first().waitFor();
    const route = key => page.locator(`.pcd-route[data-car-key="${key}"]`);
    const field = (key, name) => route(key).locator(`[data-field="${name}"]`);
    const source = path.join(__dirname, '../fixtures/files/pcd_routing.csv');
    async function upload() {
      await page.locator('input[type="file"]').setInputFiles(source);
      await page.getByRole('button', { name: 'Carregar CSV', exact: true }).click();
      await page.waitForFunction(() => document.querySelector('[data-pcd-target="importReport"]').textContent.includes('23 mapas'));
    }
    async function save(reason) {
      await page.getByRole('button', { name: 'Salvar PCD', exact: true }).click();
      await page.locator('#pcd_reason').fill(reason);
      await page.getByRole('button', { name: 'Confirmar e salvar', exact: true }).click();
      await page.waitForFunction(() => !document.querySelector('dialog[open]'));
      await page.waitForFunction(() => document.querySelector('[data-pcd-target="dirty"]').textContent.includes('nenhuma alteração pendente'));
    }
    await upload();
    assert.equal(await page.locator('.pcd-route.is-freight').count(), 6);
    assert.equal(await page.locator('.pcd-map').count(), 23);
    assert.ok((await page.locator('.pcd-room[data-room="spot"]').innerText()).includes('179795'));
    assert.equal(await field('route:0', 'plate').inputValue(), 'QJU2428');
    await route('route:0').locator('summary').click();
    assert.ok((await route('route:0').innerText()).includes('[MED]: ITAIPU (1)'));
    await page.getByRole('button', { name: 'Desfazer rascunho', exact: true }).click();
    assert.equal(await page.locator('.pcd-map').count(), 0);
    await upload();
    const duplicate = await field('route:1', 'plate').inputValue();
    await chooseSelect(page, field('route:1', 'plate'), 'QJU2428');
    assert.equal(await field('route:1', 'plate').inputValue(), duplicate);
    assert.ok((await page.locator('[data-pcd-target="message"]').innerText()).includes('já está em outra saída'));
    await chooseSelect(page, field('route:0', 'room'), 'room2');
    await field('route:0', 'departure_time').fill('09:15');
    await field('route:0', 'departure_time').blur();
    await chooseSelect(page, field('route:0', 'helper_count'), '2');
    await field('route:0', 'notes').fill('Ajuste de sala e equipe'); await field('route:0', 'notes').blur();
    const helper = page.locator('.pcd-person').filter({ hasText: 'ALBERTO' }).first();
    await helper.locator('.pcd-person-select').click();
    await route('route:0').locator('[data-role="helper2"] .pcd-vacancy').click();
    assert.ok((await route('route:0').locator('[data-role="helper2"]').innerText()).includes('ALBERTO'));
    const freighter = page.locator('.pcd-route.is-freight').first();
    const freightKey = await freighter.getAttribute('data-car-key');
    await field(freightKey, 'external_driver').fill('GABRIEL BRITO'); await field(freightKey, 'external_driver').blur();
    await save('Importação e organização por salas');
    await page.reload();
    assert.equal(await field('route:0', 'room').inputValue(), 'room2');
    assert.equal(await field('route:0', 'departure_time').inputValue(), '09:15');
    assert.equal(await field('route:0', 'helper_count').inputValue(), '2');
    await upload();
    assert.equal(await field('route:0', 'departure_time').inputValue(), '09:15');
    await save('Segunda importação do dia');
    await page.locator('.time-off-tabs').getByRole('link', { name: 'Importações', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('tab') === 'imports');
    assert.equal(await page.locator('.pcd-history-item').count(), 2);
    await page.locator('.pcd-history-item summary').first().click();
    assert.ok((await page.locator('.pcd-history-item').first().innerText()).includes('6 freteiros'));
    const pdf = await page.request.get(`${base}/pcd.pdf?date=2026-10-02`);
    assert.equal(pdf.status(), 200); assert.equal(pdf.headers()['content-type'], 'application/pdf');
    const bytes = await pdf.body(); assert.ok(bytes.toString('ascii', 0, 5) === '%PDF-');
    fs.writeFileSync('tmp/pcd/PCD_SALAS_2026-10-02.pdf', bytes);
    await page.goto(`${base}/pcd?date=2026-10-02&tab=history`);
    assert.ok((await page.locator('.pcd-panel').innerText()).includes('Impressão PCD SALAS'));
    await page.goto(`${base}/pcd?date=2026-10-02`);
    await chooseSelect(page, field('route:0', 'plate'), 'AAA1B23');
    await save('Troca de placa registrada');
    await page.goto(`${base}/pcd?date=2026-10-02&tab=history`);
    await page.locator('.pcd-history-item summary').first().click();
    assert.ok((await page.locator('.pcd-history-item').first().innerText()).includes('QJU2428 → AAA1B23'));
    await page.goto(`${base}/pcd?date=2026-10-02`);
    await page.screenshot({ path: 'tmp/pcd/desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await route('route:0').screenshot({ path: 'tmp/pcd/route_mobile.png' });
    await page.goto(`${base}/pcd?date=2026-10-03`);
    await page.locator('input[type="file"]').setInputFiles(source);
    await page.getByRole('button', { name: 'Carregar CSV', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('[data-pcd-target="message"]').textContent.includes('02/10/2026'));
    assert.equal(await page.locator('.pcd-map').count(), 0);
    assert.deepEqual(errors, []);
    console.log('PASS: PCD full import, freight, maps/regions, draft reset, plates, room/time changes, helper 2, external driver, repeated import preservation, history, PDF, wrong dates and mobile.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
