const chooseSelect = require('./helpers/select.cjs');
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');

(async () => {
  const browser = await chromium.launch();
  try {
    fs.mkdirSync('tmp/time_off', { recursive: true });
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const base = process.env.BASE_URL || 'http://127.0.0.1:4318';
    await page.emulateMedia({ reducedMotion: 'reduce' });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${base}/users/sign_in`);
    await page.locator('#user_email').fill('user_one@example.com');
    await page.locator('#user_password').fill('password');
    await page.locator('input[type="submit"]').click();
    await page.waitForURL(url => !url.pathname.includes('sign_in'));
    await page.goto(`${base}/escala-folgas?date=2026-10-02`);
    assert.equal(await page.locator('.time-off-calendar tbody tr').count(), 7);
    assert.equal(await page.locator('.time-off-tabs a').count(), 4);
    await page.evaluate(() => { window.calendarFilterMarker = 'preserved'; });
    const groupButton = group => page.locator('.time-off-group-filter').getByRole('button', { name: `Grupo ${group}`, exact: true });
    await groupButton('E').click();
    await page.waitForURL(url => url.searchParams.get('group') === 'E');
    await page.waitForFunction(() => document.querySelector('.time-off-calendar-filters input[name="group"]').value === 'E');
    assert.equal(await page.locator('.time-off-calendar tbody th').count(), 1);
    assert.equal(await groupButton('E').getAttribute('aria-pressed'), 'true');
    await groupButton('E').click();
    await page.waitForURL(url => url.searchParams.get('group') === '');
    await page.waitForFunction(() => document.querySelector('.time-off-calendar-filters input[name="group"]').value === '');
    await page.locator('#calendar-name').fill('celio');
    await page.waitForURL(url => url.searchParams.get('name') === 'celio');
    await page.waitForFunction(() => document.querySelector('.time-off-period-picker input[name="name"]').value === 'celio');
    assert.equal(await page.locator('.time-off-calendar tbody th').count(), 1);
    assert.match(await page.locator('.time-off-calendar tbody th strong').innerText(), /CELIO/);
    assert.equal(await page.locator('#calendar-name').evaluate(input => input === document.activeElement), true);
    assert.equal(await page.locator('.time-off-filters, #calendar-name.form-control, #time-off-calendar select').count(), 0);
    await page.locator('.time-off-row-picker').getByRole('button', { name: '24 linhas por página', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('per_page') === '24');
    await page.waitForFunction(() => document.querySelector('.time-off-calendar-filters input[name="per_page"]').value === '24');
    assert.equal(await page.locator('#calendar-name').inputValue(), 'celio');
    await groupButton('A').click();
    await page.waitForURL(url => url.searchParams.get('group') === 'A');
    await page.locator('.time-off-empty').waitFor();
    await page.getByRole('button', { name: 'Limpar busca', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('name') === '');
    await page.waitForFunction(() => document.querySelector('.time-off-period-picker input[name="name"]').value === '');
    assert.equal(await page.locator('.time-off-calendar tbody th').count(), 2);
    await groupButton('A').click();
    await page.waitForURL(url => url.searchParams.get('group') === '');
    await page.waitForFunction(() => document.querySelector('.time-off-calendar-filters input[name="group"]').value === '');
    await page.locator('.time-off-row-picker').getByRole('button', { name: '48 linhas por página', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('per_page') === '48');
    await page.waitForFunction(() => document.querySelector('.time-off-calendar-filters input[name="per_page"]').value === '48');
    assert.equal(await page.locator('.time-off-calendar tbody th').count(), 7);
    assert.equal(await page.evaluate(() => window.calendarFilterMarker), 'preserved');
    await page.locator('.time-off-period-picker').getByRole('button', { name: '08–14', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('calendar_period') === '2026-10-08');
    await page.waitForFunction(() => document.querySelector('.time-off-calendar-filters input[name="calendar_period"]').value === '2026-10-08');
    assert.equal(await page.locator('.time-off-row-picker button[aria-pressed="true"]').getAttribute('value'), '48');
    await page.locator('.time-off-tabs').getByRole('link', { name: 'Escala do dia', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('tab') === 'day' && url.searchParams.get('per_page') === '48');
    await page.locator('.time-off-tabs').getByRole('link', { name: 'Calendário', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('tab') === 'calendar');
    assert.equal(await page.locator('.time-off-row-picker button[aria-pressed="true"]').getAttribute('value'), '48');
    assert.equal(await page.locator('.time-off-period-picker button[aria-pressed="true"]').getAttribute('value'), '2026-10-08');
    await page.locator('.time-off-role-picker').getByRole('button', { name: 'Ajudantes', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.time-off-period-picker input[name="role"]').value === 'helper');
    assert.equal(await page.locator('.time-off-calendar tbody th').count(), 2);
    await page.locator('.time-off-role-picker').getByRole('button', { name: 'Todos', exact: true }).click();
    await page.waitForFunction(() => document.querySelector('.time-off-period-picker input[name="role"]').value === '');
    await page.locator('.time-off-month-navigation').getByRole('link', { name: 'Próximo mês', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('month') === '2026-11');
    await page.locator('.time-off-month-navigation').getByRole('link', { name: 'Mês anterior', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('month') === '2026-10');
    await page.goto(`${base}/escala-folgas?tab=day&date=2026-10-02`);
    const card = name => page.locator('.time-off-person').filter({ hasText: name });
    const list = (status, role = '') => page.locator(`.time-off-list[data-status="${status}"]${role ? `[data-role="${role}"]` : ''}`);
    assert.equal(await list('working', 'driver').locator('.time-off-person').count(), 4);
    assert.equal(await list('working', 'helper').locator('.time-off-person').count(), 2);
    assert.equal(await page.locator('.time-off-route-row, .time-off-car').count(), 0);
    assert.equal(await page.locator('[data-day-driver-gap]').innerText(), '17');
    assert.equal(await page.locator('[data-day-helper-gap]').innerText(), '17');
    async function drag(name, target) {
      const source = card(name);
      await source.scrollIntoViewIfNeeded(); await target.scrollIntoViewIfNeeded();
      const from = await source.boundingBox(), to = await target.boundingBox();
      await page.mouse.move(from.x + 10, from.y + 10); await page.mouse.down();
      await page.mouse.move(from.x + 24, from.y + 10, { steps: 5 });
      await page.mouse.move(to.x + to.width / 2, to.y + to.height - 16, { steps: 25 }); await page.mouse.up();
      await page.locator('dialog[open]').waitFor();
    }
    async function confirm(reason, status) {
      if (status) await chooseSelect(page, page.locator('select[name="change[status]"]'), status);
      const id = await page.locator('input[name="change[membership_id]"]').inputValue();
      const expected = await page.locator('select[name="change[status]"]').inputValue();
      await page.locator('textarea[name="change[reason]"]').fill(reason);
      await page.getByRole('button', { name: 'Salvar alteração', exact: true }).click();
      await page.waitForFunction(() => !document.querySelector('dialog[open]'));
      await page.waitForFunction(({ id, expected }) => document.querySelector(`.time-off-person[data-membership-id="${id}"]`)?.dataset.status === expected, { id, expected });
    }
    await drag('ADAIR DE ALMEIDA', list('unavailable'));
    await confirm('Atestado — navegador');
    await list('unavailable').locator('.time-off-person').filter({ hasText: 'ADAIR' }).waitFor();
    assert.equal(await page.locator('[data-day-driver-gap]').innerText(), '18');
    await drag('ADAIR DE ALMEIDA', list('working', 'driver'));
    await confirm('Retorno ao trabalho');
    await drag('CELIO MEDEIROS MOREIRA', list('working', 'driver'));
    await confirm('Convocação na folga');
    assert.equal(await page.locator('[data-day-driver-gap]').innerText(), '16');
    await page.locator('.time-off-tabs').getByRole('link', { name: 'Extras', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('tab') === 'extras');
    assert.ok((await page.locator('#time-off-extras').innerText()).includes('1 extra no mês'));
    await page.goto(`${base}/escala-folgas?tab=day&date=2026-10-03`);
    assert.equal(await list('off').locator('.time-off-person').filter({ hasText: 'ALBERTO' }).count(), 1);
    await page.goto(`${base}/escala-folgas?tab=day&date=2026-10-04`);
    assert.equal(await list('off').locator('.time-off-person').count(), 7);
    assert.equal(await page.locator('.time-off-shortage-summary').count(), 0);
    await page.goto(`${base}/escala-folgas?tab=day&date=2026-10-02`);
    await page.getByRole('button', { name: 'Configuração', exact: true }).click();
    await page.locator('#time-off-settings.show').waitFor();
    const form = page.locator('.time-off-vacation-form');
    await chooseSelect(page, form.locator('select'), { label: 'PATRICK VIEIRA DA SILVA · Ajudante' });
    await form.locator('input[type="date"]').first().fill('2026-10-02');
    await form.locator('input[type="date"]').last().fill('2026-10-08');
    await form.locator('textarea').fill('Férias programadas');
    await form.getByRole('button', { name: 'Registrar férias' }).click();
    await page.locator('.time-off-vacation-period').waitFor();
    await page.getByRole('button', { name: 'Fechar configuração' }).click();
    await page.locator('#time-off-settings').waitFor({ state: 'hidden' });
    assert.equal(await card('PATRICK').getAttribute('data-movable'), 'false');
    assert.equal(await page.locator('[data-day-helper-gap]').innerText(), '18');
    await page.screenshot({ path: 'tmp/time_off/availability_desktop.png', fullPage: true });
    await page.evaluate(() => localStorage.setItem('theme', 'dark')); await page.reload();
    assert.equal(await page.locator('html').getAttribute('data-bs-theme'), 'dark');
    await page.setViewportSize({ width: 390, height: 844 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
    await page.screenshot({ path: 'tmp/time_off/availability_mobile.png', fullPage: true });
    await page.goto(`${base}/escala-folgas?date=2026-10-02&calendar_period=month`);
    assert.equal(await page.locator('.time-off-cell--vacation').count(), 7);
    await page.getByRole('button', { name: 'Configuração', exact: true }).click();
    await page.locator('#time-off-settings.show').waitFor();
    await page.locator('.time-off-vacation-period summary').click();
    await page.locator('.time-off-vacation-period input[type="text"]').fill('Reagendamento');
    await page.locator('.time-off-vacation-period').getByRole('button', { name: 'Cancelar férias', exact: true }).click();
    await page.getByText('Nenhum período de férias neste mês.', { exact: true }).waitFor();
    assert.deepEqual(errors, []);
    console.log('PASS: group buttons, name search, row choices, calendar context, driver/helper availability, drag, deficits, extras, vacation, Sunday, themes and mobile.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
