const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, ignoreHTTPSErrors: true });
    const baseURL = process.env.BASE_URL || 'http://127.0.0.1:4318';
    page.setDefaultTimeout(20000);
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(`${baseURL}/users/sign_in`);
    await page.locator('#user_email').fill('user_one@example.com');
    await page.locator('#user_password').fill('password');
    await page.locator('input[type="submit"]').click();
    await page.waitForURL(url => !url.pathname.includes('sign_in'));
    await page.goto(`${baseURL}/escala-folgas?date=2026-10-02`);
    assert.equal(await page.locator('.time-off-calendar tbody tr').count(), 7);
    assert.equal(await page.locator('.time-off-board').count(), 0);
    await page.locator('.time-off-heading').evaluate(el => { el.dataset.calendarProbe = 'preserved'; });
    await page.locator('.time-off-period-picker').getByRole('button', { name: '08–14', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('calendar_period') === '2026-10-08');
    await page.waitForFunction(() => document.querySelector('.time-off-filters input[name="calendar_period"]')?.value === '2026-10-08');
    assert.equal(await page.locator('.time-off-heading').getAttribute('data-calendar-probe'), 'preserved');
    assert.equal(await page.locator('.time-off-filters input[name="calendar_period"]').inputValue(), '2026-10-08');
    assert.equal(new URL(await page.locator('.time-off-tabs a').first().getAttribute('href'), baseURL).searchParams.get('calendar_period'), '2026-10-08');
    await page.locator('.time-off-period-picker').getByRole('button', { name: '01–07', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('calendar_period') === '2026-10-01');
    await page.waitForFunction(() => document.querySelector('.time-off-period-picker button[aria-pressed="true"]')?.textContent === '01–07');
    await page.locator('.time-off-day-link').nth(1).click();
    await page.waitForURL(url => url.searchParams.get('tab') === 'day');
    assert.equal(await page.locator('.time-off-calendar').count(), 0);
    assert.equal(await page.locator('#time-off-groups').count(), 0);
    await page.locator('.time-off-person').first().waitFor();
    assert.equal(await page.locator('.time-off-person button').count(), 0);
    const working = page.locator('.time-off-column--working .time-off-person');
    const resting = page.locator('.time-off-column--off .time-off-person');
    const unavailable = page.locator('.time-off-column--unavailable .time-off-person');
    const dialog = page.locator('dialog');
    assert.equal(await working.count(), 6);
    assert.equal(await resting.count(), 1);

    async function dragPerson(person, status) {
      const source = person.locator('> strong');
      const target = page.locator(`.time-off-column--${status} .time-off-list`);
      await source.scrollIntoViewIfNeeded();
      const from = await source.boundingBox();
      await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2);
      await page.mouse.down();
      await page.mouse.move(from.x + from.width / 2 + 10, from.y + from.height / 2 + 10, { steps: 5 });
      let to = await target.boundingBox();
      const height = page.viewportSize().height;
      while (to.y + 20 >= height - 20) {
        await page.mouse.move(from.x + from.width / 2, height - 25, { steps: 5 });
        await page.mouse.wheel(0, 200);
        to = await target.boundingBox();
      }
      await page.mouse.move(to.x + to.width / 2, to.y + 20, { steps: 20 });
      await page.mouse.up();
      await dialog.waitFor({ state: 'visible' });
      assert.equal(await dialog.locator('select').inputValue(), status);
    }
    await dragPerson(working.filter({ hasText: 'ADAIR DE ALMEIDA' }), 'unavailable');
    await dialog.locator('textarea').fill('Atestado — teste de navegador');
    await dialog.getByRole('button', { name: 'Salvar alteração' }).click();
    await unavailable.filter({ hasText: 'ADAIR DE ALMEIDA' }).waitFor();
    await page.reload();
    assert.equal(await unavailable.count(), 1);
    await dragPerson(unavailable.filter({ hasText: 'ADAIR DE ALMEIDA' }), 'working');
    await dialog.locator('select').selectOption('original');
    await dialog.locator('textarea').fill('Restaurar escala no teste');
    await dialog.getByRole('button', { name: 'Salvar alteração' }).click();
    await working.filter({ hasText: 'ADAIR DE ALMEIDA' }).waitFor();

    async function dragRestingDriver() {
      await dragPerson(resting.filter({ hasText: 'CELIO MEDEIROS MOREIRA' }), 'working');
    }
    await dragRestingDriver();
    await dialog.getByRole('button', { name: 'Cancelar' }).click();
    assert.equal(await resting.count(), 1);
    assert.equal(await working.count(), 6);
    await dragRestingDriver();
    await dialog.locator('textarea').fill('Convocação na folga — teste');
    await dialog.getByRole('button', { name: 'Salvar alteração' }).click();
    await working.filter({ hasText: 'CELIO MEDEIROS MOREIRA' }).waitFor();
    assert.equal(await resting.count(), 0);
    assert.equal(await page.locator('.time-off-callout').count(), 1);
    assert.equal(new URL(page.url()).searchParams.get('tab'), 'day');
    await page.locator('.time-off-tabs').getByRole('link', { name: 'Histórico', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('tab') === 'history');
    assert.equal(await page.locator('.time-off-history li').count(), 3);
    assert.equal(await page.locator('.time-off-board').count(), 0);
    await page.getByRole('button', { name: 'Configuração', exact: true }).click();
    await page.locator('#time-off-settings.show').waitFor();
    assert.equal(await page.locator('#time-off-settings .time-off-membership-form').count(), 1);
    await page.getByRole('button', { name: 'Fechar configuração' }).click();
    await page.locator('#time-off-settings').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('.time-off-calendar').count(), 0);
    await page.locator('.time-off-tabs').getByRole('link', { name: 'Extras', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('tab') === 'extras');
    assert.ok((await page.locator('#time-off-extras').innerText()).includes('1 extra no mês'));
    await page.locator('.time-off-tabs').getByRole('link', { name: 'Escala do dia', exact: true }).click();
    await page.waitForURL(url => url.searchParams.get('tab') === 'day');
    assert.equal(new URL(page.url()).searchParams.get('date'), '2026-10-02');

    await page.goto(`${baseURL}/escala-folgas?tab=day&date=2026-10-03`);
    assert.equal(await resting.filter({ hasText: 'ALBERTO RAMON FRUTOS' }).count(), 1);
    await page.goto(`${baseURL}/escala-folgas?tab=day&date=2026-10-04`);
    assert.equal(await resting.count(), 7);
    assert.equal(await page.locator('.time-off-person button').count(), 0);

    await page.goto(`${baseURL}/escala-folgas?tab=coverage&date=2026-10-02`);
    assert.equal(await page.locator('.time-off-car').count(), 21);
    assert.equal(await page.locator('.time-off-car-group[data-operation="route"] .time-off-car').count(), 18);
    const car = key => page.locator(`.time-off-car[data-car-key="${key}"]`);
    const drop = (key, role) => car(key).locator(`[data-role="${role}"]`);
    const pool = status => page.locator(`.time-off-pool-drop[data-status="${status}"]`);
    const chip = name => page.locator('#time-off-coverage .time-off-chip').filter({ hasText: name });
    async function select(name) { await chip(name).locator('.time-off-chip-select').click(); }
    async function saveBoard(reason) {
      await page.getByRole('button', { name: 'Salvar painel', exact: true }).click();
      await page.locator('#board_reason').fill(reason);
      await page.getByRole('button', { name: 'Confirmar e salvar', exact: true }).click();
      await page.waitForFunction(() => !document.querySelector('dialog[open]'));
      await page.waitForFunction(() => document.querySelector('[data-time-off-board-target="dirty"]')?.textContent.includes('nenhuma alteração pendente'));
    }
    async function dragChip(name, target) {
      const source = chip(name).locator('.time-off-chip-select');
      await target.scrollIntoViewIfNeeded();
      await source.scrollIntoViewIfNeeded();
      const from = await source.boundingBox();
      const to = await target.boundingBox();
      await page.mouse.move(from.x + 12, from.y + 12);
      await page.mouse.down();
      await page.mouse.move(from.x + 25, from.y + 15, { steps: 5 });
      await page.mouse.move(to.x + to.width / 2, to.y + to.height / 2, { steps: 30 });
      await page.mouse.up();
    }
    assert.ok((await drop('van:0', 'driver').innerText()).includes('ADEMAR'));
    assert.ok((await drop('vespertina:0', 'helper1').innerText()).includes('ALBERTO'));
    assert.equal(await page.locator('.time-off-car-grid').first().evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length), 3);

    await select('PATRICK VIEIRA DA SILVA');
    await drop('van:0', 'driver').click();
    assert.ok((await page.locator('[data-time-off-board-target="message"]').innerText()).includes('Motorista de van'));
    assert.ok((await drop('van:0', 'driver').innerText()).includes('ADEMAR'));
    assert.equal(await chip('PATRICK VIEIRA DA SILVA').count(), 1);

    await select('ADAIR DE ALMEIDA');
    await pool('unavailable').getByRole('button', { name: 'Mover para indisponíveis' }).click();
    assert.equal(await pool('unavailable').locator('.time-off-chip').count(), 1);
    await select('CELIO MEDEIROS MOREIRA');
    await drop('route:0', 'driver').getByRole('button', { name: 'Colocar motorista' }).click();
    await saveBoard('Atestado e substituição — teste do painel');
    await page.reload();
    assert.ok((await drop('route:0', 'driver').innerText()).includes('CELIO'));
    assert.ok((await pool('unavailable').innerText()).includes('ADAIR'));

    await select('CELIO MEDEIROS MOREIRA');
    await pool('off').getByRole('button', { name: 'Mover para de folga' }).click();
    await page.getByRole('button', { name: 'Desfazer rascunho' }).click();
    assert.equal(await pool('off').locator('.time-off-chip').count(), 0);
    await select('CELIO MEDEIROS MOREIRA');
    await pool('off').getByRole('button', { name: 'Mover para de folga' }).click();
    await saveBoard('Folga compensatória — teste do painel');
    await page.reload();
    assert.equal(await pool('off').locator('.time-off-chip').count(), 1);

    await dragChip('CELIO MEDEIROS MOREIRA', drop('route:2', 'driver'));
    await drop('route:2', 'driver').locator('.time-off-chip').waitFor();
    assert.equal(await pool('off').locator('.time-off-chip').count(), 0);
    await car('route:0').locator('select').selectOption('2');
    await select('CELIO MEDEIROS MOREIRA');
    await drop('route:0', 'helper2').getByRole('button', { name: 'Colocar ajudante' }).click();
    assert.equal(await drop('route:2', 'driver').locator('.time-off-chip').count(), 0);
    await saveBoard('Convocação como segundo ajudante — teste');
    await page.reload();
    assert.equal(await car('route:0').locator('select').inputValue(), '2');
    assert.ok((await drop('route:0', 'helper2').innerText()).includes('CELIO'));
    assert.equal(await page.locator('[data-time-off-board-target="driverCount"]').innerText(), '3 / 21');
    await page.evaluate(() => scrollTo(0, 0));
    const panelAlignment = await page.locator('.time-off-car-group[data-operation="route"], .time-off-crew-pool--working').evaluateAll(els => els.map(el => ({top: el.getBoundingClientRect().top, header: el.querySelector('header').getBoundingClientRect().bottom})));
    assert.ok(Math.abs(panelAlignment[0].top - panelAlignment[1].top) < 1);
    assert.ok(Math.abs(panelAlignment[0].header - panelAlignment[1].header) < 1);
    await page.screenshot({ path: 'tmp/time_off/coverage.png', fullPage: true });
    await page.goto(`${baseURL}/escala-folgas?tab=history&date=2026-10-02`);
    assert.equal(await page.locator('.time-off-history li').count(), 9);
    await page.goto(`${baseURL}/escala-folgas?tab=coverage&date=2026-10-03`);
    assert.equal(await page.locator('.time-off-car').count(), 18);
    await page.goto(`${baseURL}/escala-folgas?tab=coverage&date=2026-10-04`);
    assert.equal(await page.locator('.time-off-car').count(), 0);
    await page.goto(`${baseURL}/escala-folgas?tab=coverage&date=2026-11-02`);
    assert.equal(await page.getByText('Sem dimensionamento vigente nesta data.', { exact: true }).count(), 1);

    await page.goto(`${baseURL}/escala-folgas?tab=day&date=2026-10-02`);
    await page.evaluate(() => localStorage.setItem('theme', 'light'));
    await page.reload();
    const columns = await page.locator('#time-off-day .time-off-column').evaluateAll(els => els.slice(0, 3).map(el => ({x: el.getBoundingClientRect().x, y: el.getBoundingClientRect().y})));
    assert.ok(columns[0].x < columns[1].x && columns[1].x < columns[2].x);
    assert.ok(columns.every(c => Math.abs(c.y - columns[0].y) < 1));
    await page.screenshot({ path: 'tmp/time_off/desktop.png', fullPage: true });
    await page.evaluate(() => localStorage.setItem('theme', 'dark'));
    await page.reload();
    assert.equal(await page.locator('html').getAttribute('data-bs-theme'), 'dark');
    await page.screenshot({ path: 'tmp/time_off/dark.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.reload();
    await dragPerson(working.first(), 'off');
    assert.equal(await dialog.isVisible(), true);
    await dialog.getByRole('button', { name: 'Cancelar' }).click();
    assert.equal(await working.first().evaluate(el => getComputedStyle(el.parentElement).display), 'grid');
    const overflow = await page.evaluate(() => ({ body: document.documentElement.scrollWidth, viewport: innerWidth }));
    assert.ok(overflow.body <= overflow.viewport + 1, JSON.stringify(overflow));
    await page.screenshot({ path: 'tmp/time_off/mobile.png', fullPage: true });
    await page.goto(`${baseURL}/escala-folgas?tab=coverage&date=2026-10-02`);
    assert.equal(await car('route:0').locator('select').inputValue(), '2');
    await select('CELIO MEDEIROS MOREIRA');
    assert.equal(await page.getByRole('button', { name: 'Cancelar seleção' }).isVisible(), true);
    await page.getByRole('button', { name: 'Cancelar seleção' }).click();
    assert.equal(await page.locator('.time-off-chip.is-selected').count(), 0);
    await select('CELIO MEDEIROS MOREIRA');
    await drop('route:3', 'driver').getByRole('button', { name: 'Colocar motorista' }).click();
    assert.ok((await drop('route:3', 'driver').innerText()).includes('CELIO'));
    await page.getByRole('button', { name: 'Desfazer rascunho' }).click();
    const coverageOverflow = await page.evaluate(() => ({ body: document.documentElement.scrollWidth, viewport: innerWidth }));
    assert.ok(coverageOverflow.body <= coverageOverflow.viewport + 1, JSON.stringify(coverageOverflow));
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: 'tmp/time_off/coverage_mobile.png', fullPage: true });
    // Vacation period blocks both day movements and car placement, and can be cancelled.
    await page.getByRole('button', { name: 'Configuração', exact: true }).click();
    await page.locator('#time-off-settings.show').waitFor();
    const vacationForm = page.locator('.time-off-vacation-form');
    await vacationForm.locator('select').selectOption({ label: 'PATRICK VIEIRA DA SILVA · Ajudante' });
    await vacationForm.locator('input[type="date"]').first().fill('2026-10-02');
    await vacationForm.locator('input[type="date"]').last().fill('2026-10-08');
    await vacationForm.locator('textarea').fill('Férias programadas — navegador');
    await vacationForm.getByRole('button', { name: 'Registrar férias' }).click();
    await page.locator('.time-off-vacation-period').waitFor();
    await page.locator('#time-off-settings.show').waitFor();
    await page.getByRole('button', { name: 'Fechar configuração' }).click();
    await page.locator('#time-off-settings').waitFor({ state: 'hidden' });
    const vacationChip = chip('PATRICK VIEIRA DA SILVA');
    assert.equal(await vacationChip.locator('.time-off-vacation-badge').innerText(), 'Férias');
    assert.equal(await vacationChip.locator('.time-off-chip-select').isDisabled(), true);
    assert.equal(await drop('route:0', 'helper1').locator('.time-off-chip').count(), 0);
    await page.goto(`${baseURL}/escala-folgas?tab=day&date=2026-10-02`);
    const vacationPerson = unavailable.filter({ hasText: 'PATRICK VIEIRA DA SILVA' });
    assert.equal(await vacationPerson.getAttribute('data-movable'), 'false');
    assert.equal(await vacationPerson.locator('button').count(), 0);
    await page.goto(`${baseURL}/escala-folgas?date=2026-10-02&calendar_period=month`);
    assert.equal(await page.locator('.time-off-cell--vacation').count(), 7);
    assert.equal(await page.locator('.time-off-group-legend .time-off-group-summary').count(), 7);
    assert.equal(await page.locator('.time-off-tabs').getByRole('link', { name: 'Grupos', exact: true }).count(), 0);
    await page.getByRole('button', { name: 'Configuração', exact: true }).click();
    await page.locator('#time-off-settings.show').waitFor();
    await page.screenshot({ path: 'tmp/time_off/configuration_mobile.png', fullPage: true });
    await page.locator('.time-off-vacation-period summary').click();
    await page.locator('.time-off-vacation-period input[type="text"]').fill('Período reagendado — navegador');
    await page.locator('.time-off-vacation-period').getByRole('button', { name: 'Cancelar férias', exact: true }).click();
    await page.getByText('Nenhum período de férias neste mês.', { exact: true }).waitFor();
    await page.locator('#time-off-settings.show').waitFor();
    await page.getByRole('button', { name: 'Fechar configuração' }).click();
    await page.locator('#time-off-settings').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('.time-off-cell--vacation').count(), 0);
    assert.deepEqual(errors, []);
    console.log('PASS: tabs, absence/restore/drag, interactive car board, fixed crews/van validation, call-up, absence, per-car helper slots, persistence, draft reset, Saturday/Sunday, missing period, mobile, themes, configuration offcanvas, monthly extras and vacation registration/cancellation');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
